/*
 * This file is generated by jOOQ.
 */
package com.nextbank.account.infrastructure.jooq;


import com.nextbank.account.infrastructure.jooq.tables.Accounts;
import com.nextbank.account.infrastructure.jooq.tables.Outbox;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_ACCOUNTS_CUSTOMER_ID = Internal.createIndex(DSL.name("idx_accounts_customer_id"), Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.CUSTOMER_ID }, false);
    public static final Index IDX_OUTBOX_UNPUBLISHED = Internal.createIndex(DSL.name("idx_outbox_unpublished"), Outbox.OUTBOX, new OrderField[] { Outbox.OUTBOX.PUBLISHED, Outbox.OUTBOX.OCCURRED_AT }, false);
}
