package com.nextbank.account.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.Currency;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.AssertionsForClassTypes.assertThatThrownBy;

class AccountTest {

    private static final CustomerId CUSTOMER = new CustomerId("cus_test_001");
    private static final Iban IBAN = new Iban("ES9121000418450200051332");
    private static final Currency EUR = Currency.getInstance("EUR");

    private Account newAccount(){
        return Account.open(CUSTOMER, IBAN, EUR);
    }

    @Nested
    @DisplayName("Account Opening")
    class Opening{
        @Test
        @DisplayName("A new account is created with no balance")
        void newAccountStartsWithZeroBalance(){
            Account account = newAccount();

            assertThat(account.getBalance()).isEqualByComparingTo(BigDecimal.ZERO);
        }

        @Test
        @DisplayName("A new account gets an autogenerated id")
        void newAccountGetsGeneratedId(){
            Account account = newAccount();

            assertThat(account.getAccountId()).isNotNull();
            assertThat(account.getAccountId().value()).startsWith("acc_");
        }

        @Test
        @DisplayName("Two new accounts have different id's")
        void twoNewAccountsHaveDifferentIds(){
            assertThat(newAccount().getAccountId()).isNotEqualTo(newAccount().getAccountId());
        }

        @Test
        @DisplayName("An account starts with version zero")
        void accountStartsWithZeroVersionZero(){
            assertThat(newAccount().getVersion()).isZero();
        }

    }

    @Nested
    @DisplayName("Crediting")
    class Crediting{
        @Test
        @DisplayName("Credit increase balance")
        void creditIncreaseBalance(){
            Account account = newAccount();
            account.credit(new BigDecimal("100.00"));
            assertThat(account.getBalance()).isEqualByComparingTo("100.00");
        }

        @Test
        @DisplayName("Successive credits accumulate")
        void successiveCreditsAccumulate(){
            Account account = newAccount();
            account.credit(new BigDecimal("100.00"));
            account.credit(new BigDecimal("50.00"));
            assertThat(account.getBalance()).isEqualByComparingTo("150.00");

        }

        @Test
        @DisplayName("Cannot credit zero")
        void cannotCreditZero(){
            Account account = newAccount();

            assertThatThrownBy(() -> account.credit(BigDecimal.ZERO))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("must be positive");
        }

        @Test
        @DisplayName("Cannot credit negative amount")
        void cannotCreditNegativeAmount(){
            Account account = newAccount();

            assertThatThrownBy(() -> account.credit(new BigDecimal("-10.00")))
                    .isInstanceOf(IllegalArgumentException.class);
        }
    }

    @Nested
    @DisplayName("Debits")
    class Debiting {

        @Test
        @DisplayName("Debit decreases balance")
        void debitDecreasesBalance() {
            Account account = newAccount();
            account.credit(new BigDecimal("200.00"));

            account.debit(new BigDecimal("75.25"));

            assertThat(account.getBalance()).isEqualByComparingTo("124.75");
        }

        @Test
        @DisplayName("Can debit entire balance")
        void canDebitEntireBalance() {
            Account account = newAccount();
            account.credit(new BigDecimal("100.00"));

            account.debit(new BigDecimal("100.00"));

            assertThat(account.getBalance()).isEqualByComparingTo(BigDecimal.ZERO);
        }

        @Test
        @DisplayName("no se puede cargar mas que el saldo disponible")
        void cannotDebitMoreThanBalance() {
            Account account = newAccount();
            account.credit(new BigDecimal("50.00"));

            assertThatThrownBy(() -> account.debit(new BigDecimal("50.01")))
                    .isInstanceOf(InsufficientFundsException.class);
        }

        @Test
        @DisplayName("un cargo rechazado deja el saldo intacto")
        void rejectedDebitLeavesBalanceUnchanged() {
            Account account = newAccount();
            account.credit(new BigDecimal("50.00"));

            assertThatThrownBy(() -> account.debit(new BigDecimal("100.00")))
                    .isInstanceOf(InsufficientFundsException.class);

            assertThat(account.getBalance()).isEqualByComparingTo("50.00");
        }

        @Test
        @DisplayName("no se puede cargar sobre una cuenta sin saldo")
        void cannotDebitFromEmptyAccount() {
            Account account = newAccount();

            assertThatThrownBy(() -> account.debit(new BigDecimal("0.01")))
                    .isInstanceOf(InsufficientFundsException.class);
        }

        @Test
        @DisplayName("el error de saldo insuficiente informa del importe y el disponible")
        void insufficientFundsErrorCarriesAmounts() {
            Account account = newAccount();
            account.credit(new BigDecimal("30.00"));

            assertThatThrownBy(() -> account.debit(new BigDecimal("80.00")))
                    .hasMessageContaining("80")
                    .hasMessageContaining("30");
        }
    }

    @Nested
    @DisplayName("Precision decimal")
    class DecimalPrecision {

        @Test
        @DisplayName("las operaciones con decimales no pierden precision")
        void decimalOperationsKeepPrecision() {
            Account account = newAccount();

            account.credit(new BigDecimal("0.10"));
            account.credit(new BigDecimal("0.20"));

            // con double esto daria 0.30000000000000004
            assertThat(account.getBalance()).isEqualByComparingTo("0.30");
        }

        @Test
        @DisplayName("se conservan los cuatro decimales de precision")
        void keepsFourDecimalPlaces() {
            Account account = newAccount();

            account.credit(new BigDecimal("100.1234"));
            account.debit(new BigDecimal("0.0234"));

            assertThat(account.getBalance()).isEqualByComparingTo("100.1000");
        }
    }



}
