/*
 * This file is generated by jOOQ.
 */
package com.nextbank.account.infrastructure.jooq.tables.records;


import com.nextbank.account.infrastructure.jooq.tables.Accounts;

import java.math.BigDecimal;
import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountsRecord extends UpdatableRecordImpl<AccountsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.accounts.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.accounts.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.accounts.customer_id</code>.
     */
    public void setCustomerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.accounts.customer_id</code>.
     */
    public String getCustomerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.accounts.iban</code>.
     */
    public void setIban(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.accounts.iban</code>.
     */
    public String getIban() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.accounts.currency</code>.
     */
    public void setCurrency(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.accounts.currency</code>.
     */
    public String getCurrency() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.accounts.balance</code>.
     */
    public void setBalance(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.accounts.balance</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.accounts.opened_at</code>.
     */
    public void setOpenedAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.accounts.opened_at</code>.
     */
    public Instant getOpenedAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.accounts.version</code>.
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.accounts.version</code>.
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountsRecord
     */
    public AccountsRecord() {
        super(Accounts.ACCOUNTS);
    }

    /**
     * Create a detached, initialised AccountsRecord
     */
    public AccountsRecord(String id, String customerId, String iban, String currency, BigDecimal balance, Instant openedAt, Long version) {
        super(Accounts.ACCOUNTS);

        setId(id);
        setCustomerId(customerId);
        setIban(iban);
        setCurrency(currency);
        setBalance(balance);
        setOpenedAt(openedAt);
        setVersion(version);
        resetTouchedOnNotNull();
    }
}
