/*
 * This file is generated by jOOQ.
 */
package com.nextbank.account.infrastructure.jooq.tables.records;


import com.nextbank.account.infrastructure.jooq.tables.Outbox;

import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxRecord extends UpdatableRecordImpl<OutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.outbox.event_id</code>.
     */
    public void setEventId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.outbox.event_id</code>.
     */
    public String getEventId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.outbox.event_type</code>.
     */
    public void setEventType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.outbox.event_type</code>.
     */
    public String getEventType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.outbox.aggregate_id</code>.
     */
    public void setAggregateId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.outbox.aggregate_id</code>.
     */
    public String getAggregateId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.outbox.aggregate_type</code>.
     */
    public void setAggregateType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.outbox.aggregate_type</code>.
     */
    public String getAggregateType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.outbox.payload</code>.
     */
    public void setPayload(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.outbox.payload</code>.
     */
    public String getPayload() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.outbox.occurred_at</code>.
     */
    public void setOccurredAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.outbox.occurred_at</code>.
     */
    public Instant getOccurredAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.outbox.published</code>.
     */
    public void setPublished(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.outbox.published</code>.
     */
    public Boolean getPublished() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.outbox.correlation_id</code>.
     */
    public void setCorrelationId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.outbox.correlation_id</code>.
     */
    public String getCorrelationId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.outbox.causation_id</code>.
     */
    public void setCausationId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.outbox.causation_id</code>.
     */
    public String getCausationId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutboxRecord
     */
    public OutboxRecord() {
        super(Outbox.OUTBOX);
    }

    /**
     * Create a detached, initialised OutboxRecord
     */
    public OutboxRecord(String eventId, String eventType, String aggregateId, String aggregateType, String payload, Instant occurredAt, Boolean published, String correlationId, String causationId) {
        super(Outbox.OUTBOX);

        setEventId(eventId);
        setEventType(eventType);
        setAggregateId(aggregateId);
        setAggregateType(aggregateType);
        setPayload(payload);
        setOccurredAt(occurredAt);
        setPublished(published);
        setCorrelationId(correlationId);
        setCausationId(causationId);
        resetTouchedOnNotNull();
    }
}
