spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/nextbank_account
    username: nextbank
    password: nextbank
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

nextbank:
  outbox:
    poll-interval-ms: 2000

server:
  port: 8081

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
